// Books data remains the same as your original page
const books = [
  {
    id: '1',
    title: 'Active Inference',
    author: ['Thomas Parr,', ' Giovanni Pezzulo,', ' Karl J. Friston,'],
    description: ['Active inference is a way of understanding sentient behavior—a theory that characterizes perception, planning, and action in terms of probabilistic inference. Developed by theoretical neuroscientist Karl Friston over years of groundbreaking research, active inference provides an integrated perspective on brain, cognition, and behavior that is increasingly used across multiple disciplines including neuroscience, psychology, and philosophy. Active inference puts the action into perception. This book offers the first comprehensive treatment of active inference, covering theory, applications, and cognitive domains. Active inference is a “first principles” approach to understanding behavior and the brain, framed in terms of a single imperative to minimize free energy. The book emphasizes the implications of the free energy principle for understanding how the brain works. It first introduces active inference both conceptually and formally, contextualizing it within current theories of cognition. It then provides specific examples of computational models that use active inference to explain such cognitive phenomena as perception, attention, memory, and planning.'],
    coverImage: '/images/books/Active-Inference.jpg',
    category: 'Science',
    rating: 5,
    amazonLink: 'https://www.amazon.com/Active-Inference-Energy-Principle-Behavior/dp/0262045354',
  },
  {
    id: '2',
    title: 'Big Sur',
    author: 'Jack Kerouac',
    description: ['Five years after On the Road, the book that made him an overnight celebrity, Kerouac examines with wrenching clarity his unwished for fame, escalating alcoholism, and troubling alienation from nature. In a thinly veiled autobiographical account of his time in Big Sur at the cabin of Lawrence Ferlinghetti and with friends in San Francisco—among them fellow iconoclasts Neal Cassady, Gary Snyder, and Alan Watts—he chronicles a ruinous alcoholic bender with searing psychological candor. Kerouac displays full mastery of pace, structure, and idiom in Big Sur—a tale that ends with a crescendo as finely wrought and poignant as any in American literature. This Warbler Classics annotated edition includes a character key and a detailed biographical timeline.'],
    coverImage: '/images/books/Big-Sur.jpg',
    category: 'Novel',
    rating: 5,
    amazonLink: 'https://www.amazon.com/Big-Sur-Jack-Kerouac/dp/1734029269/ref=pd_lpo_d_sccl_1/138-0259292-4831654?psc=1',
  },
  {
    id: '3',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    description: ['Aldous Huxley\'s profoundly important classic of world literature, Brave New World is a searching vision of an unequal, technologically-advanced future where humans are genetically bred, socially indoctrinated, and pharmaceutically anesthetized to passively uphold an authoritarian ruling order–all at the cost of our freedom, full humanity, and perhaps also our souls. “A genius [who] who spent his life decrying the onward march of the Machine” (The New Yorker), Huxley was a man of incomparable talents: equally an artist, a spiritual seeker, and one of history’s keenest observers of human nature and civilization. Brave New World, his masterpiece, has enthralled and terrified millions of readers, and retains its urgent relevance to this day as both a warning to be heeded as we head into tomorrow and as thought-provoking, satisfying work of literature. Written in the shadow of the rise of fascism during the 1930s, Brave New Worldd likewise speaks to a 21st-century world dominated by mass-entertainment, technology, medicine and pharmaceuticals, the arts of persuasion, and the hidden influence of elites.'],
    coverImage: '/images/books/Brave-New-World.jpg',
    category: 'Dystopian Novel',
    rating: 4,
    amazonLink: 'https://www.amazon.com/Brave-New-World-Aldous-Huxley/dp/0060850523',
  },
  {
    id: '4',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    description: 'An insightful look at how our background, experiences, and emotions shape our relationship with money. Contains timeless lessons on wealth and happiness.',
    coverImage: '/images/books/Breath.jpg',
    category: 'Finance',
    rating: 5,
    amazonLink: 'https://www.amazon.com/Psychology-Money-Timeless-lessons-happiness/dp/0857197681/',
  },
  {
    id: '5',
    title: 'Atomic Habits',
    author: 'James Clear',
    description: 'A practical guide to building good habits and breaking bad ones. The concepts in this book have helped me improve my productivity and consistency.',
    coverImage: '/images/books/Chaos.jpg',
    category: 'Productivity',
    rating: 4,
    amazonLink: 'https://www.amazon.com/Atomic-Habits-Proven-Build-Break/dp/0735211299/',
  },
  {
    id: '6',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    description: 'An excellent deep dive into the principles of designing systems that handle data at scale. Essential reading for any software engineer working with data systems.',
    coverImage: '/images/books/Chip-War.jpg',
    category: 'Technology',
    rating: 5,
    amazonLink: 'https://www.amazon.com/Designing-Data-Intensive-Applications-Reliable-Maintainable/dp/1449373321/',
  },
];

export default books;